# for local development
version: '3.7'
services:
  fuelinginfinity:
    build: .
    ports:
      - '3000:3000'
      - '10000:10000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '../manugo:/app/node_modules/manugo'
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    command: /bin/sh -c "yarn dev"
